version: '3.8'

services:

  mysql-db:
    image: mysql:8.0
    container_name: innovatech-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: RootSecurePassword123!
      MYSQL_DATABASE: innovatech_db
      MYSQL_USER: innovatech_user
      MYSQL_PASSWORD: UserPassword123!

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - back-network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5


  backend-ventas:
    image: danielx1/backend-ventas:v1
    container_name: backend-ventas-service
    restart: unless-stopped

    environment:
      DB_ENDPOINT: mysql-db
      DB_PORT: 3306
      DB_NAME: innovatech_db
      DB_USERNAME: innovatech_user
      DB_PASSWORD: UserPassword123!

    ports:
      - "8080:8080"

    networks:
      - back-network

    depends_on:
      mysql-db:
        condition: service_healthy


  backend-despacho:
    image: danielx1/backend-despacho:v1
    container_name: backend-despacho-service
    restart: unless-stopped

    environment:
      DB_ENDPOINT: mysql-db
      DB_PORT: 3306
      DB_NAME: innovatech_db
      DB_USERNAME: innovatech_user
      DB_PASSWORD: UserPassword123!

    ports:
      - "8081:8081"

    networks:
      - back-network

    depends_on:
      mysql-db:
        condition: service_healthy


  frontend:
    image: danielx1/frontend-despacho:v1
    container_name: frontend-react-app
    restart: unless-stopped

    ports:
      - "80:8080"

    networks:
      - front-network
      - back-network

    depends_on:
      - backend-ventas
      - backend-despacho


volumes:
  mysql_data:


networks:
  front-network:
  back-network: