name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  backend-despacho:
    runs-on: self-hosted
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend despacho
        run: |
          docker build -t danielx1/backend-despacho:v1 "./proyecto semestral/back-Despachos_SpringBoot"

      - name: Push backend despacho
        run: |
          docker push danielx1/backend-despacho:v1

  backend-ventas:
    runs-on: self-hosted
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend ventas
        run: |
          docker build -t danielx1/backend-ventas:v1 "./proyecto semestral/back-Ventas_SpringBoot"

      - name: Push backend ventas
        run: |
          docker push danielx1/backend-ventas:v1

  frontend:
    runs-on: self-hosted
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build frontend
        run: |
          docker build -t danielx1/frontend-despacho:v1 "./proyecto semestral/front_despacho"

      - name: Push frontend
        run: |
          docker push danielx1/frontend-despacho:v1

  deploy-ec2:
    runs-on: self-hosted
    needs:
      - backend-despacho
      - backend-ventas
      - frontend
    steps:
      - name: Desplegar en AWS EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: 10m  # Le da hasta 10 minutos de gracia al SSH
          script: |
            mkdir -p /home/ubuntu/ISY1101_EP2_Proyecto_Semestral
            cd /home/ubuntu/ISY1101_EP2_Proyecto_Semestral
            
            # Descarga el docker-compose actualizado
            wget -O docker-compose.yml https://raw.githubusercontent.com/${{ github.repository }}/main/proyecto%20semestral/docker-compose.yml
            
            # Forzamos la descarga de las imágenes frescas
            sudo docker compose pull
            
            # Apagamos lo anterior limpiando huellas viejas
            sudo docker compose down --remove-orphans
            
            # Levantamos en segundo plano (-d) de forma limpia
            sudo docker compose up -d --force-recreate
